/**
 * Dense retrieval tier for AJP In-Operation mode.
 * Loads pre-computed embeddings from public/ajp-corpus.json (generated by
 * scripts/ingest-corpus.ts) and performs cosine similarity lookup.
 *
 * Swappable backend pattern: setDenseBackend() lets callers substitute a
 * Supabase pgvector store, Pinecone, or any other provider without touching
 * the retrieval call sites. Defaults to the bundled JSON file.
 *
 * When the active domain has no dense corpus (graph-only domains, or
 * pre-ingestion), all queries return empty results and the system falls back
 * to graph-only retrieval transparently.
 */
import { getActiveDomain } from '../../domains/domain-context';

// ─── Types ────────────────────────────────────────────────────────

/** A single chunk from an ingested source document. */
export interface DenseChunk {
  id: string;
  /** Human-readable source label (e.g. "Stanford SNF SOP"). */
  source: string;
  /** Section heading or context within the source. */
  section: string;
  /** Raw chunk text (300–500 words). */
  text: string;
  /** Gemini text-embedding-004 vector (768 dimensions). */
  embedding: number[];
  /** Optional: linked AJP graph node id if this chunk maps to a known node. */
  linkedNodeId?: string;
}

/** A scored match returned by a dense query. */
export interface DenseMatch {
  chunk: DenseChunk;
  score: number;
}

/** Swappable dense retrieval backend. */
export interface DenseBackend {
  /** Return top-K chunks most similar to the query embedding. */
  query(queryEmbedding: number[], topK: number): Promise<DenseMatch[]>;
  /** True if this backend has any indexed data. */
  hasData(): boolean;
  /**
   * Identifier for the embedding model that produced the indexed vectors
   * (e.g. 'text-embedding-004'). Callers must only issue queries from a
   * provider with a matching modelId — otherwise cosine scores are
   * meaningless because query and doc vectors live in different spaces.
   */
  modelId(): string | undefined;
}

// ─── Cosine Similarity ────────────────────────────────────────────

function cosine(a: number[], b: number[]): number {
  let dot = 0, na = 0, nb = 0;
  for (let i = 0; i < a.length; i++) {
    dot += a[i] * b[i];
    na += a[i] * a[i];
    nb += b[i] * b[i];
  }
  const denom = Math.sqrt(na) * Math.sqrt(nb);
  return denom === 0 ? 0 : dot / denom;
}

// ─── In-Memory JSON Backend ───────────────────────────────────────

/** State for the lazy-loaded JSON backend. */
let _chunks: DenseChunk[] | null = null;
let _corpusModel: string | undefined = undefined;
let _loadPromise: Promise<DenseChunk[]> | null = null;

/**
 * Load and cache corpus chunks from public/ajp-corpus.json.
 * Concurrent callers share the same in-flight promise — critical for a
 * multi-MB corpus file, where the fetch can take seconds and several
 * components (Dashboard, RAG Coverage, a live query) may all call this
 * before the first one resolves. A prior version tracked only a boolean
 * "attempted" flag, so any caller arriving during that window resolved to
 * a stale `[]` instead of the eventual real data — see git history.
 */
function loadChunks(): Promise<DenseChunk[]> {
  if (_chunks !== null) return Promise.resolve(_chunks);
  if (_loadPromise) return _loadPromise;

  _loadPromise = (async () => {
    const ref = getActiveDomain().denseCorpus?.corpusUrl;
    if (!ref) {
      console.info('[DenseRetrieval] Active domain has no dense corpus — graph-only mode');
      return (_chunks = []);
    }

    try {
      const res = await fetch(`${import.meta.env.BASE_URL}${ref}`);
      if (!res.ok) {
        console.error(`[DenseRetrieval] Corpus fetch failed: ${ref} → HTTP ${res.status}`);
        return (_chunks = []);
      }
      // Guard against the SPA fallback: a missing file behind try_files
      // returns 200 + index.html, and res.json() would throw with a message
      // that hides the real cause.
      const contentType = res.headers.get('content-type') ?? '';
      if (contentType.includes('text/html')) {
        console.error(
          `[DenseRetrieval] Corpus fetch for ${ref} returned HTML (SPA fallback) — file missing from the deploy`,
        );
        return (_chunks = []);
      }
      const data = await res.json() as { chunks?: DenseChunk[]; model?: string };
      _chunks = Array.isArray(data.chunks) ? data.chunks : [];
      _corpusModel = data.model;
      console.info(
        `[DenseRetrieval] Loaded ${_chunks.length} corpus chunks from ${ref} (model: ${_corpusModel ?? 'unknown'})`,
      );
      return _chunks;
    } catch (err) {
      console.error(`[DenseRetrieval] Corpus load failed for ${ref}:`, err);
      return (_chunks = []);
    }
  })();

  return _loadPromise;
}

/** Lightweight chunk metadata (no embedding/text) for coverage analysis. */
export interface ChunkInventoryItem {
  id: string;
  source: string;
  section: string;
}

/**
 * Return id/source/section for every loaded corpus chunk, dropping the heavy
 * embedding and text fields. Reuses the same cached load as queryDense(), so
 * the RAG Coverage view can enumerate the full corpus (to find never-retrieved
 * chunks) without a second 22 MB parse. Empty array when no corpus is loaded.
 */
export async function loadChunkInventory(): Promise<ChunkInventoryItem[]> {
  const chunks = await loadChunks();
  return chunks.map(({ id, source, section }) => ({ id, source, section }));
}

const jsonBackend: DenseBackend = {
  async query(queryEmbedding, topK) {
    const chunks = await loadChunks();
    if (chunks.length === 0) return [];
    return chunks
      .map((chunk) => ({ chunk, score: cosine(queryEmbedding, chunk.embedding) }))
      .sort((a, b) => b.score - a.score)
      .slice(0, topK);
  },
  hasData() {
    return _chunks !== null && _chunks.length > 0;
  },
  modelId() {
    return _corpusModel;
  },
};

// ─── Backend Registry ─────────────────────────────────────────────

let _backend: DenseBackend = jsonBackend;

/**
 * Override the default JSON backend with a custom store.
 * Call this in App.tsx to wire in Supabase pgvector, Pinecone, etc.
 *
 * Example (Supabase):
 *   import { createSupabaseBackend } from './supabase-backend';  // future file
 *   setDenseBackend(createSupabaseBackend(supabaseUrl, supabaseKey));
 */
export function setDenseBackend(backend: DenseBackend): void {
  _backend = backend;
}

export function getDenseBackend(): DenseBackend {
  return _backend;
}

// ─── Public Query API ─────────────────────────────────────────────

export interface DenseRetrievalQuery {
  /** Pre-computed query embedding from the embedding provider. */
  queryEmbedding: number[];
  /**
   * ModelId of the provider that produced queryEmbedding. Dense retrieval
   * will refuse to score against indexed vectors from a different model,
   * since cosine between mismatched vector spaces is meaningless.
   */
  queryModelId?: string;
  /** Maximum number of chunks to return. Default 5. */
  topK?: number;
  /** Minimum cosine similarity to include. Default 0.3. */
  minScore?: number;
}

export interface DenseRetrievalResult {
  matches: DenseMatch[];
  hasData: boolean;
  /** True iff dense was skipped because query/doc model ids disagree. */
  modelMismatch?: boolean;
}

// ─── Lexical Fallback Query ───────────────────────────────────────

/**
 * TF-IDF lexical scoring over chunk *text*, for providers whose vectors
 * can't be compared against the baked corpus embeddings (the simulated
 * TF-IDF provider has no modelId and emits per-call vector spaces). This
 * keeps the dense corpus reachable in no-key/simulated mode: matches are
 * genuine keyword-overlap hits on the ingested SOP text, not semantic
 * neighbors, and callers should label them as such.
 */
let _lexicalIndex: { docTerms: Map<string, number>[]; docFreq: Map<string, number> } | null = null;

function tokenizeLexical(text: string): string[] {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, ' ')
    .split(/\s+/)
    .filter((t) => t.length > 2);
}

function buildLexicalIndex(chunks: DenseChunk[]) {
  const docTerms: Map<string, number>[] = [];
  const docFreq = new Map<string, number>();
  for (const chunk of chunks) {
    const tf = new Map<string, number>();
    const tokens = tokenizeLexical(`${chunk.section} ${chunk.text}`);
    for (const t of tokens) tf.set(t, (tf.get(t) ?? 0) + 1);
    for (const t of tf.keys()) docFreq.set(t, (docFreq.get(t) ?? 0) + 1);
    docTerms.push(tf);
  }
  return { docTerms, docFreq };
}

export interface LexicalRetrievalQuery {
  queryText: string;
  topK?: number;
  /** Minimum normalized lexical score to include. Default 0.05. */
  minScore?: number;
}

/**
 * Query the dense corpus by TF-IDF keyword overlap with the query text.
 * Loads the corpus if needed. Scores are cosine over TF-IDF weights,
 * normalized to 0–1 — not comparable to embedding-cosine scores.
 */
export async function queryDenseLexical(query: LexicalRetrievalQuery): Promise<DenseRetrievalResult> {
  const { queryText, topK = 5, minScore = 0.05 } = query;
  const chunks = await loadChunks();
  if (chunks.length === 0) return { matches: [], hasData: false };

  if (!_lexicalIndex || _lexicalIndex.docTerms.length !== chunks.length) {
    _lexicalIndex = buildLexicalIndex(chunks);
  }
  const { docTerms, docFreq } = _lexicalIndex;
  const n = chunks.length;

  const qtf = new Map<string, number>();
  for (const t of tokenizeLexical(queryText)) qtf.set(t, (qtf.get(t) ?? 0) + 1);
  if (qtf.size === 0) return { matches: [], hasData: true };

  const idf = (term: string) => Math.log((n + 1) / ((docFreq.get(term) ?? 0) + 1)) + 1;
  let qNorm = 0;
  const qWeights = new Map<string, number>();
  for (const [t, c] of qtf) {
    const w = c * idf(t);
    qWeights.set(t, w);
    qNorm += w * w;
  }
  qNorm = Math.sqrt(qNorm);

  const scored = chunks.map((chunk, i) => {
    const tf = docTerms[i];
    let dot = 0;
    let dNorm = 0;
    for (const [t, c] of tf) {
      const w = c * idf(t);
      dNorm += w * w;
      const qw = qWeights.get(t);
      if (qw) dot += qw * w;
    }
    dNorm = Math.sqrt(dNorm);
    const score = qNorm > 0 && dNorm > 0 ? dot / (qNorm * dNorm) : 0;
    return { chunk, score };
  });

  const matches = scored
    .filter((m) => m.score >= minScore)
    .sort((a, b) => b.score - a.score)
    .slice(0, topK);
  return { matches, hasData: true };
}

/** Query the dense corpus tier. Returns empty results if no data is loaded. */
export async function queryDense(query: DenseRetrievalQuery): Promise<DenseRetrievalResult> {
  const { queryEmbedding, queryModelId, topK = 5, minScore = 0.3 } = query;
  const backend = getDenseBackend();

  // Ensure the corpus (if any) has finished loading before checking readiness —
  // loadChunks() memoizes, so this is a no-op await once it has resolved.
  await loadChunks();

  if (!backend.hasData()) {
    return { matches: [], hasData: false };
  }

  // An undefined queryModelId means the provider's vectors live in a per-call
  // space (simulated TF-IDF) — those must never be cosine'd against baked
  // embeddings either. The old `corpusModel && queryModelId &&` guard let
  // undefined slip through: TF-IDF vectors were scored against 3072-dim
  // Gemini vectors, producing NaN scores and silently-empty results.
  const corpusModel = backend.modelId();
  if (corpusModel && corpusModel !== queryModelId) {
    console.warn(
      `[DenseRetrieval] Skipping dense tier — corpus model "${corpusModel}" does not match query provider "${queryModelId ?? '(no modelId)'}" — use queryDenseLexical for keyword fallback`,
    );
    return { matches: [], hasData: true, modelMismatch: true };
  }

  const matches = await backend.query(queryEmbedding, topK);
  const filtered = matches.filter((m) => m.score >= minScore);
  return { matches: filtered, hasData: true };
}
